### ISSUE TITLE
error when using number as column name

### ISSUE THREAD

**Issue by metter** [alexandrainst/node-red-contrib-postgresql#10]
I receive the following error message:
```
error: syntax error at or near "`" UPDATE people
SET `5`='{"pet":"dog"}'
WHERE id = '5';
```
The syntax seems correct

**Comment by Alkarex** [comment]
I do not believe backticks are acceptable in PostgreSQL. See https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

Try instead with no quotes or double-quotes:

```sql
UPDATE people
SET "5"='{"pet":"dog"}'
WHERE id = '5';
```
