### ISSUE TITLE
Server connection pool getting filled by idle "wait: ClientRead" connections when sending queries rapidly

### ISSUE THREAD

**Issue by robacarp** [alexandrainst/node-red-contrib-postgresql#21]
Hey, thanks for this node-red node. I was able to get it up and running pretty quick, but I'm running into a small issue. Simple insert queries are hanging when fired off too fast. It causes the connection pool on the server to fill up, which causes later queries to fail due to `"Error: timeout exceeded when trying to connect"`.

A workaround is to add a rate-limit delay node, which tells me that something is getting forgotten when more than one query is being run at a time. I believe this would be insufficient if I had many query nodes in my flows because any collision would leave a connection hanging and eventually lead to pool exhaustion.

I'm not doing anything too clever. Postgres is installed and connected over 127.0.0.1, and it's a clean install of Postgres 14. No other applications are connecting at this time -- I have shut down grafana, which is the only other thing connected to the server.

My query is this: 

```sql
INSERT INTO "public"."metrics"
("name", "metric", "units", "type")
VALUES('{{{ msg.topic }}}', {{{ msg.payload.value }}}, 'ºF', '{{{ msg.payload.name }}}')
```

It gets expanded correctly and is received by postgres like this, which I pulled from the query log:

```sql
INSERT INTO "public"."metrics"
("name", "metric", "units", "type")
VALUES('Sensor 2', 39.46, 'ºF', 'temperature')
```

The first batch of events query node execute fine and data ends up in the table. But the n-1 queries never finishes and the connection is left hanging open:

```sql
> psql
psql (14.0)
Type "help" for help.

robert=# select client_addr, wait_event, state, query from pg_stat_activity;
 client_addr |     wait_event      | state  |                                                               query
-------------+---------------------+--------+-----------------------------------------------------------------------------------------------------------------------------------
             | AutoVacuumMain      |        | 
             | LogicalLauncherMain |        | 
             |                     | active | select client_addr, wait_event, state, query from pg_stat_activity;
 127.0.0.1   | ClientRead          | active | INSERT INTO "public"."metrics" ("name", "metric", "units", "type") VALUES('Sensor 1', 60.35, 'ºF', 'temperature')
 127.0.0.1   | ClientRead          | idle   | INSERT INTO "public"."metrics" ("name", "metric", "units", "type") VALUES('Sensor 2', 39.46, 'ºF', 'temperature')
 127.0.0.1   | ClientRead          | active | INSERT INTO "public"."metrics" ("name", "metric", "units", "type") VALUES('Sensor 2', 39.46, 'ºF', 'temperature')
 127.0.0.1   | ClientRead          | idle   | INSERT INTO "public"."metrics" ("name", "metric", "units", "type") VALUES('Sensor 2', 39.46, 'ºF', 'temperature')
             | BgWriterMain        |        | 
             | CheckpointerMain    |        | 
             | WalWriterMain       |        | 
(10 rows)

```

These connections listed here will never close -- triggering my flow again fires 5 queries and 4 of them will never correctly finish. 

Here are some screenshots:

<details><summary>
Node-Red flow:
</summary>
<img src="https://user-images.githubusercontent.com/208647/153248757-aeb63629-d83f-44d7-82dc-2794e547fc66.png">
</details>

<details><summary>
A working node-red flow:
</summary>
<img src="https://user-images.githubusercontent.com/208647/153250102-24436a86-2d62-434d-9d4b-90b45a1539c8.png">
</details>

**Comment by ahanselka** [comment]
I'm having a similar issue to @robacarp, except mine seems to be getting caught up with `SELECT` statements. It doesn't happen super often or cause me huge problems, but I figured I'd note that it can happen with lots of `SELECT` as well. 🙂

**Comment by Alkarex** [comment]
If you have a scenario during which you have a burst of many requests during a short time period, you can increase the *Connection Timeout* parameter (in milliseconds):

![image](https://user-images.githubusercontent.com/1008324/155016196-f4d74667-4be3-4689-b292-6d0bdcda7766.png)

It of course depends on the number of requests and the time the SQL requests take to be executed by PostgreSQL.

So for safely processing a large number of requests at maximum speed, I advise using the built-in [backpressure](https://github.com/alexandrainst/node-red-contrib-postgresql#backpressure) mechanism whenever possible.

**Comment by ahanselka** [comment]
@robacarp I started having the same issue with INSERTS. What I did is use the `batch` and `join` nodes to aggregate the readings in 10 second intervals, then used a `function` node  with [knex](https://knexjs.org/) to generate a `msg.query` for the Postgres node. It helped substantially given that I had gotten up to several inserts per second. Now I end up doing one insert every 10 or so seconds with 14 or so records each time and have not experienced any further issue.

**Comment by wangnick** [comment]
Similar issue over here. Under some conditions node-red-contrib-postgresql gets stuck in dangling queries and any further request is rejected with "Error: timeout exceeded when trying to connect". In my case the connection pool settings are the default 10, idle timeout 1000ms, connection timeout 10000ms, and the backlog when stuck is e.g.:
```
 127.0.0.1     | ClientRead | idle   | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
 127.0.0.1     | ClientRead | idle   | select count(*) as count, percentile_disc(0.2) within group (order by pond_mm) as pond_mm  FROM t5_valvebox where ts>=now()-interval '3 hour' and no=6
 127.0.0.1     | ClientRead | idle   | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
 127.0.0.1     | ClientRead | idle   | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
 127.0.0.1     | ClientRead | idle   | select count(*) as count, percentile_disc(0.2) within group (order by pond_mm) as pond_mm  FROM t5_valvebox where ts>=now()-interval '3 hour' and no=6
 127.0.0.1     | ClientRead | idle   | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
 127.0.0.1     | ClientRead | idle   | select count(*) as count, percentile_disc(0.2) within group (order by pond_mm) as pond_mm  FROM t5_valvebox where ts>=now()-interval '3 hour' and no=6
 127.0.0.1     | ClientRead | active | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
 127.0.0.1     | ClientRead | active | select count(*) as count, percentile_disc(0.2) within group (order by pond_mm) as pond_mm  FROM t5_valvebox where ts>=now()-interval '3 hour' and no=6
 127.0.0.1     | ClientRead | idle   | select extract(year from CURRENT_DATE) as year, extract(month from CURRENT_DATE) as month, extract(day from CURRENT_DATE) as day, min(ts), max(ts), count(*) as count, sum(case when soil_status='WET' then 1 else 0 end) as wet, sum(case when soil_status='DRY' then 1 else 0 end) as dry from t5_valvebox where no=6 and ts>=CURRENT_DATE+interval '6 hour' and ts<CURRENT_DATE+interval '7 hour'
```

It seems as if the connection pool does not get cleaned up properly under certain conditions ...

**Comment by wangnick** [comment]
> It seems as if the connection pool does not get cleaned up properly under certain conditions ...

My bad. For exactly those nodes firing the queries listed above as dangling I activated "Split results in multiple messages" to ease my post-processing of the single row returned, not recognising that this also activates backpressure management. So seemingly the node was waiting to receive a tick such that it would only then return the connection to the pool with no further rows available. Sorry for the noise ...

Kind regards,
Sebastian

**Comment by Alkarex** [comment]
@wangnick Thanks for the update 👍🏻 Let me know if you spot another issue

**Comment by Alkarex** [comment]
A performance issue has been fixed by https://github.com/alexandrainst/node-red-contrib-postgresql/pull/25 , which might also positively impact the problems discussed here
