### ISSUE TITLE
How to globally set the application name?

### ISSUE THREAD

**Issue by ondics** [alexandrainst/node-red-contrib-postgresql#23]
In the version 0.9.0 the [application name can be set](https://flows.nodered.org/node/node-red-contrib-postgresql) for each node using

```
msg.pgConfig = {
  application_name?: string,
}
```

But how to set the application name globally over all nodes. In the server settings of the postgresql-node there is no field "application name".

**Comment by Alkarex** [comment]
Ok, I have to admit that this is not something I have been using myself in PostgreSQL, but I will expose it in the global parameters (or PR welcome).

References:
* https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-APPLICATION-NAME
* https://node-postgres.com/api/client

**Comment by Alkarex** [comment]
@ondics Would you be able to try https://github.com/alexandrainst/node-red-contrib-postgresql/pull/24 ?

**Comment by TimoB2005** [comment]
It worked. Thank you!

**Comment by Alkarex** [comment]
New release https://github.com/alexandrainst/node-red-contrib-postgresql/releases/tag/v0.10.1
Tests welcome
