### ISSUE TITLE
Crashing on nodered 2.22

### ISSUE THREAD

**Issue by gocamiot** [alexandrainst/node-red-contrib-postgresql#26]
Morn. So latest docker nodered image, if I install your posgres node, nodered runs ok. If i drag and drop on workspace, nodered keeps on crashing. Before even I put credentials.

Your node is awesome bro. I use it on thousand flows. Please help.
btw. I run the latest docker image. SO please test on docker image.
Regards

Jakes

**Comment by gocamiot** [comment]
Update.
I install latest docker image and make it run.
I add postgressql in pallet. (all ok)
I drag and drop on workspace. Nodered starts to restart. (postgressql node not configured yet, so it shows invalid)
I configure noderedsql and deploy until eventually nodered accepts.
nodered restarts once more and then runs normally.
Hope you can recreate issue. For now Ill continue like that.
Ciao

**Comment by Alkarex** [comment]
Thanks for the bug report. I will fix ASAP.
Meanwhile, my guess is that the node needs to be configured (e.g. database parameters) before deploying.

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/alexandrainst/node-red-contrib-postgresql/commit/83f494525c70f2323803fb5158b4abbe1e53d0d4
New release coming

**Comment by Alkarex** [comment]
Version 0.11.2 released https://github.com/alexandrainst/node-red-contrib-postgresql/releases/tag/v0.11.2
Feedback welcome
