### ISSUE TITLE
node-red-contrib-postgresql crashes on Citrix virtualized Windows 10 desktop host but not on physical Linux host

### ISSUE THREAD

**Issue by YitzHandel** [alexandrainst/node-red-contrib-postgresql#36]
I am trying to migrate my flows from a physical Linux (Ubuntu) host to a Citrix virtualized Windows 10 desktop host.
Even the simplest flow containing postgresql crashes when triggered.
Interestingly, node-red-contrib-postgres-variable does not crash.

On the Windows environment, which is virtualized via Citrix, I used Powershell to globally install nsm and all the nsm packages, and used the node-red pallete manage to install the same palette as on Linux / node-red.

The linux is a physical laptop.

I have attached both flows.

In the Windows system, clicking either of these crashes node-red, and I have to remove the flows in .node-red in my user directory and import or start over.

![image](https://user-images.githubusercontent.com/47528427/213937674-76f31568-55a2-47f5-ba8c-469f0285f8c1.png)

But injecting to the (green) -variable ones work.
![image](https://user-images.githubusercontent.com/47528427/213937962-ffc57a3b-b2ff-4b14-a81e-8f14451853a0.png)

[two postgresql flows.zip](https://github.com/alexandrainst/node-red-contrib-postgresql/files/10475371/two.postgresql.flows.zip)

**Comment by Alkarex** [comment]
Hello and sorry for the delay.
If you are still around, was that with version 0.12.0, and could you share any error information you might have from your logs?
