### ISSUE TITLE
Abrupt termination after some time running - [error] Error: Connection terminated unexpectedly

### ISSUE THREAD

**Issue by ItsVitor** [alexandrainst/node-red-contrib-postgresql#49]
Hello!

Being unable to find a solution there, I'm bringing this issue here from [my post](https://discourse.nodered.org/t/abrupt-termination-after-some-time-running-error-error-connection-terminated-unexpectedly/80973) in Node-RED forum. I figured since the error happens at the pg lib, I might find a clarification here.

I've been using Node-RED with Docker, trying to run the flow below:

![flow node-red](https://github.com/alexandrainst/node-red-contrib-postgresql/assets/79506366/375005d7-aa31-4130-9ce7-5e037cb37072)

It's a simple flow: get some data from this postgres db, do something, then insert the data into this other postgres db.

This is the error I was having: 

```
1 Sep 13:39:40 - [red] Uncaught Exception:
1 Sep 13:39:40 - [error] Error: Connection terminated unexpectedly
at Connection. (/data/node_modules/pg/lib/client.js:132:73)
at Object.onceWrapper (node:events:627:28)
at Connection.emit (node:events:513:28)
at Socket. (/data/node_modules/pg/lib/connection.js:63:12)
at Socket.emit (node:events:513:28)
at TCP. (node:net:301:12)
```
No exception was caught by the catch:all node in my flow and Node-RED just terminates.

When I run the same flow, also with Docker using my laptop, it works, it keeps running with no problems. For reference, this PC with the error uses Windows 10, my laptop uses Windows 11.

Something odd happened, though. Trying to uncover where the error was happening in my flow, I:

1. Removed the inserts from my flow and let it run;
2. Attested it was running for some time (hours) without terminating;
3. Added back the inserts, goal to test and reproduce the termination;
4. Attested that the program ran 2,5 days straight with no problems, until I terminated it this morning.

I mean, it is working now, but still couldn't figure it out that error and sudden termination, and I'm afraid it could come back.

**Node-red version**: 3.0.2
**Node-js version**: 16.20.1
**node-red-contrib-posgresql version**: 0.13.0

Any clarification or insight would be very appreciated and I'm here to provide further information. Thanks!

**Comment by workin-at-the-car-walsh** [comment]
Hi @ItsVitor 

What version of postgresql database are you running?

I had this working when reading and writing to postgresql 13.7, then when I upgraded to 15.4 the insert queries resulted in this error appearing.

My node, node-red and postgres package are the same major version

Still looking into it but came across your issue. Do you have any further information?

**Comment by Alkarex** [comment]
@ItsVitor Thanks for the bug report. Would you be able to test https://github.com/alexandrainst/node-red-contrib-postgresql/pull/50 ?

**Comment by Alkarex** [comment]
New release https://github.com/alexandrainst/node-red-contrib-postgresql/releases/tag/v0.14.0
Feedback welcome
