### ISSUE TITLE
dynamic global and flow variables

### ISSUE THREAD

**Issue by fellinga** [alexandrainst/node-red-contrib-postgresql#7]
Hi, and thank you for this node!
I have to address different postgres server, therefore I tried to set the HOST via "flow" or "global" variables.

If I change the HOST to "flow.sqlip" and deploy the flow, I immediately receive an error in the debug area:
![123](https://user-images.githubusercontent.com/26927863/135284696-1c5af553-9ac9-4174-b46c-445072ef389b.png)

Deploying with "global.sqlip" does not throw an error in the debug area but unfortunately it does not work as well if the variable gets updated while the flow is running. Example: Lets say global.sqlip is set to 10.0.0.15 and the flow is deployed, after some time global.sqlip gets updated to 10.0.0.18 (programmatically) without redeploying -> then I receive a connection timeout because the node still try's to connect to 10.0.0.15 (I think).

Is this is a known issue?

**Comment by Alkarex** [comment]
I have removed the *flow* config option in a new release 0.3.0 just published (tests welcome).

For *global*, I have made a draft of patch, but not tested at all (no time until next week) https://github.com/alexandrainst/node-red-contrib-postgresql/pull/8
Tests and additional input welcome.

**Comment by fellinga** [comment]
I updated to 0.3.0, went well, but it still doesn't connect to the latest global value. I have even added a delay node to verify that the global has been set.

**Comment by Alkarex** [comment]
> I updated to 0.3.0, went well, but it still doesn't connect to the latest global value. I have even added a delay node to verify that the global has been set.

@fellinga Yes, as mentioned regarding global, please check https://github.com/alexandrainst/node-red-contrib-postgresql/pull/8 if you can

**Comment by fellinga** [comment]
Sorry I kind of thought 0.3.0 did include the change. I just applied the patch and now I receive the following error:
TypeError: Cannot read property 'host' of undefined

Additional thought / feature request: It would be a lot easier for me (maybe for others as well) if I could just send a message with something like msg.host = 10.0.0.12 to the postgres node.

**Comment by Alkarex** [comment]
> Additional thought / feature request: It would be a lot easier for me (maybe for others as well) if I could just send a message with something like msg.host = 10.0.0.12 to the postgres node.

Yes, that should be possible to implement

**Comment by Alkarex** [comment]
Implemented in https://github.com/alexandrainst/node-red-contrib-postgresql/pull/9
Tests welcome
