### ISSUE TITLE
[QUESTION] Protection against SQL-Injections

### ISSUE THREAD

**Issue by RotatingGiraffe** [alexandrainst/node-red-contrib-postgresql#80]
Hello,

from what I saw while skimming through the repository and documentation, this Node does not have built-in protection against SQL-Injections, correct?
So if I want a secure app, I would have to manually sanitize my inputs beforehand?

**Comment by RotatingGiraffe** [comment]
I decided to just try and do an Injection into my database using this node - there is no protection.
You could document this somehwere, just so that people that maybe don't think about security a lot get a heads up.

Thank you for your work on this node :)

**Comment by Alkarex** [comment]
The node's job is precisely to run arbitrary SQL commands.
However, just like in other systems, you should use parameterized queries when working with untrusted variables: https://github.com/alexandrainst/node-red-contrib-postgresql/blob/main/README.md#parameterized-query-numeric
