### ISSUE TITLE
Using a custom CA for SSL

### ISSUE THREAD

**Issue by juansolanop** [alexandrainst/node-red-contrib-postgresql#83]
Can you please provide recommendations on how to add a custom CA to be use for SSL?

I'm using Linode Postgress DB Cluster and it requires a custom CA to validate the Cert.

It will be also ok if I can skip the cert validation

**Comment by Alkarex** [comment]
Hello,
Can this help? https://github.com/alexandrainst/node-red-contrib-postgresql/discussions/81

**Comment by juansolanop** [comment]
Thank you, that solved the issue
